### ISSUE TITLE
Errors after updating to 2.1.1: getTime is not a function

### ISSUE THREAD

**Issue by Ben305** [jagi/meteor-astronomy#460]
After updating to 2.1.1, I see the following errors:

Client:

<pre>TypeError: m._d.getTime is not a function
    at valid__isValid (packages/momentjs_moment.js?hash=fdd2a686acbcdab86367e144226084ee2f26a4c1:144:38)
    at Moment.moment_valid__isValid [as isValid] (packages/momentjs_moment.js?hash=fdd2a686acbcdab86367e144226084ee2f26a4c1:2533:16)
    at Moment.toJSON (packages/momentjs_moment.js?hash=fdd2a686acbcdab86367e144226084ee2f26a4c1:2529:21)
    at Object.stringify (native)
    at Object.EJSON.stringify (packages/ejson.js?hash=b1036d3e150ea4ea6470ea9cd45a48a12835d57e:373:17)
    at toJSONValue (packages/jagi_astronomy.js?hash=1072231fadcd7f39cd28e113202e18ef887a9446:2636:24)
    at packages/jagi_astronomy.js?hash=1072231fadcd7f39cd28e113202e18ef887a9446:1580:5
    at arrayEvery (packages/jagi_astronomy.js?hash=1072231fadcd7f39cd28e113202e18ef887a9446:11118:12)
    at Function.every (packages/jagi_astronomy.js?hash=1072231fadcd7f39cd28e113202e18ef887a9446:19218:14)
    at Class.dispatchEvent (packages/jagi_astronomy.js?hash=1072231fadcd7f39cd28e113202e18ef887a9446:1579:23)
</pre>

Server:

<pre>
Error: Object [object Object] has no method 'getTime'
    at valid__isValid (packages/momentjs_moment/moment.js:116:1)
    at Moment.moment_valid__isValid [as isValid] (packages/momentjs_moment/moment.js:2505:1)
    at Moment.toJSON (packages/momentjs_moment/moment.js:2501:1)
    at Object.stringify (native)
    at Object.stringify (/Users/Ben/.meteor/packages/ecmascript-runtime/.0.2.12.1tuubj++os+web.browser+web.cordova/npm/node_modules/meteor-ecmascript-runtime/node_modules/core-js/modules/es6.symbol.js:127:21)
    at Object.EJSON.stringify (packages/ejson/ejson.js:343:1)
    at toJSONValue (packages/jagi:astronomy/lib/modules/fields/class_events/to_json_value.js:5:24)
    at packages/jagi:astronomy/lib/modules/events/class_prototype_methods/dispatch_event.js:41:5
    at arrayEvery (/Users/Ben/.meteor/packages/jagi_astronomy/.2.1.1.zem136++os+web.browser+web.cordova/npm/node_modules/lodash/lodash.js:526:12)
    at Function.every (/Users/Ben/.meteor/packages/jagi_astronomy/.2.1.1.zem136++os+web.browser+web.cordova/npm/node_modules/lodash/lodash.js:8626:14)
</pre>

Reverting to 2.1.0 fixes all these errors.

**Comment by Ben305** [comment]
Nevermind, the error was in my code. I set moment objects instead of DateTime, that's why these errors occurred.
